# Commands to start on workspace startup
tasks:
  - init: pip install streamlit
  - init: pip install plotly
  - init: pip install statsmodels
  - init: pip install pandas
  - init: pip install Pillow
    command: streamlit run app.py
# Ports to expose on workspace startup
ports:
  - port: 8501
    onOpen: open-preview